/*

 */
package Login;

import Menu.Main;
import Placeholder.TextPrompt;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Johan Tavera
 */
public class Login extends javax.swing.JFrame {
    String loginUsuario,passUsuario;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        TextPrompt placeholderUsuario= new TextPrompt("Ingrese su usuario",txtUsuario);
        TextPrompt placeholderPassword= new TextPrompt("Ingrese su contraseña",passflPass);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        passflPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        lblIngresar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setForeground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblIniciarSesion.setText("INICIAR SESIÓN");
        panelLogin.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario");
        panelLogin.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setBorder(null);
        panelLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 20));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 15));
        panelLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 230, 10));

        lblPassword.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblPassword.setText("Contraseña");
        panelLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        passflPass.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        passflPass.setBorder(null);
        passflPass.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        passflPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passflPassActionPerformed(evt);
            }
        });
        panelLogin.add(passflPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, 20));
        panelLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 10));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        lblIngresar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblIngresar.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngresar.setText("INGRESAR");
        lblIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelLogin.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lblCerrar.setBackground(new java.awt.Color(0, 0, 0));
        lblCerrar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setText("CERRAR");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelLogin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passflPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passflPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passflPassActionPerformed

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIngresarMouseClicked
        boolean encontrado=false;
        boolean correcto=false;
        if(txtUsuario.getText().equals(""))
            JOptionPane.showMessageDialog(panelLogin, "El campo de usuario está vacío");
        else if(passflPass.getPassword().length==0)
            JOptionPane.showMessageDialog(panelLogin, "El campo de contraseña está vacío");
        else{
            //Lo de abajo no lo descomentes que no creo que funcione en tu máquina
            
            loginUsuario=txtUsuario.getText();
            passUsuario=new String(passflPass.getPassword());//Se crea un objeto String con el contenido del campo jPasswordField
            File archivoUsuarios= new File("C:\\ProyectoFinalLabProg2\\src\\main\\java\\ArchivosDeTexto\\archivoUsuarios.txt");
            try {                           
                if(!archivoUsuarios.exists())
                    archivoUsuarios.createNewFile();
                BufferedReader br =new BufferedReader(new FileReader(archivoUsuarios));
                BufferedWriter bw=new BufferedWriter(new FileWriter(archivoUsuarios));
                bw.write("admin; root");
                bw.newLine();
                bw.write("kkk; ooo");
                bw.newLine();
                bw.flush();
                Scanner s= new Scanner(archivoUsuarios);
                while(s.hasNext())
                {
                    String linea=s.nextLine();
                    Scanner sl= new Scanner(linea);
                    sl.useDelimiter("\\s*;\\s*");
                    if(loginUsuario.equals(sl.next()))
                    {
                        encontrado=true;
                        if(passUsuario.equals(sl.next()))
                        {
                            correcto=true;
                            JOptionPane.showMessageDialog(panelLogin, "Bienvenido al sistema");
                            this.dispose();
                            //Lo de abajo es para que pase al menú principal
                            Main main= new Main();
                            main.setVisible(true);
                        }
                    }
                }
                if(!encontrado||!correcto)
                    JOptionPane.showMessageDialog(panelLogin, "Usuario o contraseña incorrecto");
                
            } 
            catch (FileNotFoundException e)
            {
                JOptionPane.showMessageDialog(panelLogin, "Archivo de texto no encontrado");
            } catch (IOException ex) 
            {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_lblIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField passflPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
