
package form;

import java.awt.Color;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PanelConsultaCobroPorRangoFecha extends javax.swing.JPanel {
    
    public static final SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    DefaultTableModel Tabla;
    public static Date fechaDesde;
    public static Date fechaHasta;
    public static Date fechaAux;
    
    public PanelConsultaCobroPorRangoFecha() {
        initComponents();
        Tabla=( DefaultTableModel)this.jTable1.getModel();
        jTable1.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Consultar = new javax.swing.JButton();
        desdeTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtPorNombre1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 30));

        desdeTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(desdeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 140, 30));

        jLabel1.setText("Desde");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 600, 10));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Id cobro", "Id cliente", "Cobro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 600, 190));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        txtPorNombre1.setEditable(false);
        txtPorNombre1.setBackground(new java.awt.Color(0, 0, 0));
        txtPorNombre1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        txtPorNombre1.setForeground(new java.awt.Color(255, 255, 255));
        txtPorNombre1.setText("Consulta de Cobro Por Rango de Fecha");
        txtPorNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(txtPorNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPorNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        Tabla.setRowCount(0);
        String idCobro,fecha,idCliente,cobro;
        File arch= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoCobros.txt");
        try
        {
            if(arch.exists())
            {
                if(!desdeTxt.getText().isEmpty())
                    {
                        String fechaBruta=desdeTxt.getText();
                        String[] separada=fechaBruta.split("/");
                        try {
                            if(Integer.parseInt(separada[0])>0&&Integer.parseInt(separada[0])<32&&
                                    Integer.parseInt(separada[1])>0&&Integer.parseInt(separada[1])<13&&
                                    Integer.parseInt(separada[2])>1900)
                            {
                                try 
                                {
                                    fechaDesde=formato.parse((fechaBruta));
                                    System.out.println(formato.format(fechaDesde));
                                } 
                                catch (ParseException ex) {
                                    ex.printStackTrace();
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"Formato de fecha incorrecto","Formato de fecha incorrecto",JOptionPane.ERROR_MESSAGE);
                                desdeTxt.setText("");
                            }
                        }
                        catch (Exception e) {
                            JOptionPane.showMessageDialog(null,"Solo se pueden poner números del 0 al 9","Formato de fecha incorrecto",JOptionPane.ERROR_MESSAGE);
                            desdeTxt.setText("");
                        }
                    }
                
                        String linea;
                        
                        Scanner s;
                        if(desdeTxt.getText().isEmpty())
                        {
                            s = new Scanner(arch);
                            while (s.hasNextLine())
                            {
                                linea = s.nextLine();
                                Scanner k = new Scanner(linea);
                                k.useDelimiter("\\s*;\\s*");
                                idCobro=k.next();
                                fecha=k.next();
                                idCliente=k.next();
                                cobro=k.next();
                                Tabla.addRow(new Object [] {fecha,idCobro,idCliente,cobro});

                            }//FIN while

                        s.close();
                        }
                        else 
                        {
                            s = new Scanner(arch);
                            while (s.hasNextLine())
                            {
                                linea = s.nextLine();
                                Scanner k = new Scanner(linea);
                                k.useDelimiter("\\s*;\\s*");
                                idCobro=k.next();
                                fecha=k.next();
                                idCliente=k.next();
                                cobro=k.next();
                                System.out.println("1 0");
                                fechaAux=formato.parse(fecha);
                                if(fechaDesde.before(fechaAux))
                                Tabla.addRow(new Object [] {fecha,idCobro,idCliente,cobro});
                            }
                            s.close();
                        }
                
            }
        }
        catch(Exception x)
        {
            System.out.println(x);
        }
    }//GEN-LAST:event_ConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JTextField desdeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPorNombre1;
    // End of variables declaration//GEN-END:variables
}
