
package form;

import Placeholder.TextPrompt;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Marte
 */
public class PanelReservaActividades extends javax.swing.JPanel {
    public static String sAntiguaLinea="";
    public static String sNuevaLinea="";
    public static boolean crear;
    public static Date fechaR;
    public static Date fechaB;
    public static final SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form PanelReservaActividades
     */
    public PanelReservaActividades() {
        initComponents();
        TextPrompt placeholderIdReservaAct= new TextPrompt("Obligatorio, debe contener 8 dígitos",idReservaActividadTxt);
        TextPrompt placeholderFechaReserva= new TextPrompt("Obligatorio     DD/MM/AAAA",fechaReservaTxt);
        TextPrompt placeholderFechaBaja= new TextPrompt("Obligatorio    DD/MM/AAAA",fechaBajaTxt);
        TextPrompt placeholderIdEstadoReserva= new TextPrompt("Obligatorio, debe contener 8 dígitos",idEstadoReservaActTxt);
        TextPrompt placeholderIdClienteReservaAct= new TextPrompt("Obligatorio, debe contener 8 dígitos",idClienteReservaActTxt);
        TextPrompt placeholderIdActividad= new TextPrompt("Obligatorio, debe contener 8 dígitos",idActividadTxt);
        TextPrompt placeholderIdRerservaHoraAct= new TextPrompt("Obligatorio, debe contener 8 dígitos",idReservaHoraActTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idActividadTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        idEstadoReservaActTxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        fechaBajaTxt = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        lblAgregar = new javax.swing.JLabel();
        lblDinamico = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idClienteReservaActTxt = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        idReservaHoraActTxt = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        idReservaActividadTxt = new javax.swing.JTextField();
        fechaReservaTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Registrar nueva reserva de actividad");
        jLabel10.setOpaque(true);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Reserva Actividad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        idActividadTxt.setForeground(new java.awt.Color(153, 153, 153));
        idActividadTxt.setBorder(null);
        add(idActividadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 233, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Fecha Reserva");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID Estado Reserva Actividad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        idEstadoReservaActTxt.setForeground(new java.awt.Color(153, 153, 153));
        idEstadoReservaActTxt.setBorder(null);
        add(idEstadoReservaActTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 233, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 10, 400));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Fecha Baja");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        fechaBajaTxt.setForeground(new java.awt.Color(153, 153, 153));
        fechaBajaTxt.setBorder(null);
        add(fechaBajaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 233, 20));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 250, 10));

        lblAgregar.setBackground(new java.awt.Color(0, 0, 0));
        lblAgregar.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setText("AGREGAR");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setOpaque(true);
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });
        add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 130, 40));
        add(lblDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 80, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("ID Cliente Reserva Actividad");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        idClienteReservaActTxt.setForeground(new java.awt.Color(153, 153, 153));
        idClienteReservaActTxt.setBorder(null);
        add(idClienteReservaActTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 233, 20));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 250, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("ID actividad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 250, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("ID Reserva Hora Actividad ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, 20));

        idReservaHoraActTxt.setForeground(new java.awt.Color(153, 153, 153));
        idReservaHoraActTxt.setBorder(null);
        add(idReservaHoraActTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 233, 20));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 250, 10));

        idReservaActividadTxt.setForeground(new java.awt.Color(153, 153, 153));
        idReservaActividadTxt.setBorder(null);
        idReservaActividadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReservaActividadTxtActionPerformed(evt);
            }
        });
        add(idReservaActividadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 233, 20));

        fechaReservaTxt.setForeground(new java.awt.Color(153, 153, 153));
        fechaReservaTxt.setBorder(null);
        add(fechaReservaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 233, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void idReservaActividadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReservaActividadTxtActionPerformed
        int cod;
        cod=Integer.parseInt(idReservaActividadTxt.getText());
        boolean encontrado=false;
        File f= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoReservaActividades.txt");
        Scanner s;  
        Scanner sl=null;
            try {
                
                if(!f.exists())
                    f.createNewFile();
                
                try {
                    s= new Scanner(f);
                    while(s.hasNext()&&!encontrado)
                {
                    String linea=s.nextLine();
                    sl= new Scanner(linea);
                    sl.useDelimiter("\\s*;\\s*");
                    try 
                    {
                        if(cod==Integer.parseInt(sl.next())){
                        fechaReservaTxt.setText(sl.next());
                        fechaBajaTxt.setText(sl.next());
                        idEstadoReservaActTxt.setText(sl.next());
                        idClienteReservaActTxt.setText(sl.next());
                        idActividadTxt.setText(sl.next());
                        idReservaHoraActTxt.setText(sl.next());
                            
                        lblDinamico.setText("Modificando");
                        sAntiguaLinea=(idReservaActividadTxt.getText()+";"+fechaReservaTxt.getText()+";"+fechaBajaTxt.getText()+";"+
                        idEstadoReservaActTxt.getText()+";"+idClienteReservaActTxt.getText()+";"+idActividadTxt.getText()+";"+idReservaHoraActTxt.getText());
                        encontrado=true;
                        crear=true;
                    }
                    else{
                        lblDinamico.setText("Creando");
                        fechaReservaTxt.setText("");
                        idActividadTxt.setText("");
                        fechaBajaTxt.setText("");
                        idEstadoReservaActTxt.setText("");
                        idClienteReservaActTxt.setText("");
                        idActividadTxt.setText("");
                        idReservaHoraActTxt.setText("");
                        crear=false;
                    }
                    } 
                    catch (Exception e) {
                        System.out.println("Error al leer el archivo ");
                        e.printStackTrace();
                    }
                }
                s.close();
                sl.close();
                } catch (NullPointerException e) {
                    lblDinamico.setText("Creando");
                }
            } 
            catch (IOException ex) 
            {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_idReservaActividadTxtActionPerformed

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        try {
            boolean vacio=true;
            File f= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoReservaActividades.txt");
            if(!f.exists())
                f.createNewFile();
            
            if(idReservaActividadTxt.getText().equals("")||idReservaHoraActTxt.getText().equals("")||fechaBajaTxt.getText().equals("")
                    ||fechaReservaTxt.getText().equals("")||idClienteReservaActTxt.getText().equals("")||idActividadTxt.getText().equals("")
                    ||idEstadoReservaActTxt.getText().equals(""))
                vacio=false;
            if(!idEstadoReservaActTxt.getText().matches("[0-9]{8}"))
            {
                vacio=false;
                idEstadoReservaActTxt.setText("");
                JOptionPane.showMessageDialog(null,"El id del estado de la reserva solo acepta valores númericos enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                File archId= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoEstadoReserva.txt");
                if (!archId.exists()) 
                {
                    JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                    vacio=false;
                }
                else
                {
                    int cod;
                    cod=Integer.parseInt(idEstadoReservaActTxt.getText());
                    if(!revisarEnArchivo(archId, cod))
                    {
                        idEstadoReservaActTxt.setText("");
                        JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                        vacio=false;
                    }
                }
            }
            
            if(!idReservaActividadTxt.getText().matches("[0-9]{8}"))
            {
                vacio=false;
                idReservaActividadTxt.setText("");
                JOptionPane.showMessageDialog(null,"El id de reserva solo acepta valores númericos enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            
            if(!idClienteReservaActTxt.getText().matches("[0-9]{8}"))
            {
                vacio=false;
                idClienteReservaActTxt.setText("");
                JOptionPane.showMessageDialog(null,"El id del cliente solo acepta valores númericos enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                File archId= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoClientes.txt");
                if (!archId.exists()) 
                {
                    JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                    vacio=false;
                }
                else
                {
                    int cod;
                    cod=Integer.parseInt(idClienteReservaActTxt.getText());
                    if(!revisarEnArchivo(archId, cod))
                    {
                        idClienteReservaActTxt.setText("");
                        JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                        vacio=false;
                    }
                }
            }
            
            if(!idActividadTxt.getText().matches("[0-9]{8}"))
            {
                vacio=false;
                idActividadTxt.setText("");
                JOptionPane.showMessageDialog(null,"El id de la actividad solo acepta valores númericos enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                File archId= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoActividades.txt");
                if (!archId.exists()) 
                {
                    JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                    vacio=false;
                }
                else
                {
                    int cod;
                    cod=Integer.parseInt(idActividadTxt.getText());
                    if(!revisarEnArchivo(archId, cod))
                    {
                        idActividadTxt.setText("");
                        JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                        vacio=false;
                    }
                }
            }
            
            if(!idReservaHoraActTxt.getText().matches("[0-9]{8}"))
            {
                vacio=false;
                idReservaHoraActTxt.setText("");
                JOptionPane.showMessageDialog(null,"El id del horario solo acepta valores númericos enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                File archId= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoHorarioActividades.txt");
                if (!archId.exists()) 
                {
                    JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                    vacio=false;
                }
                else
                {
                    int cod;
                    cod=Integer.parseInt(idReservaHoraActTxt.getText());
                    if(!revisarEnArchivo(archId, cod))
                    {
                        idReservaHoraActTxt.setText("");
                        JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                        vacio=false;
                    }
                }
            }
            
            if(!fechaReservaTxt.getText().isEmpty())
            {
                
                String fechaBruta=fechaReservaTxt.getText();
                String[] separada=fechaBruta.split("/");
                try {
                    if(Integer.parseInt(separada[0])>0&&Integer.parseInt(separada[0])<32&&
                            Integer.parseInt(separada[1])>0&&Integer.parseInt(separada[1])<13&&
                            Integer.parseInt(separada[2])>2000)
                    {
                        try 
                        {
                            fechaR=formato.parse((fechaBruta));
                            System.out.println(formato.format(fechaR));
                        } 
                        catch (ParseException ex) {
                            ex.printStackTrace();
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Formato de fecha incorrecto","Formato de fecha incorrecto",JOptionPane.ERROR_MESSAGE);
                        fechaReservaTxt.setText("");
                        vacio=false;
                    }
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Solo se pueden poner números del 0 al 9","Formato de fecha incorrecto",JOptionPane.ERROR_MESSAGE);
                    fechaReservaTxt.setText("");
                    vacio=false;
                }
            }
            if(!fechaBajaTxt.getText().isEmpty())
            {
                
                String fechaBruta=fechaBajaTxt.getText();
                String[] separada=fechaBruta.split("/");
                try {
                    if(Integer.parseInt(separada[0])>0&&Integer.parseInt(separada[0])<32&&
                            Integer.parseInt(separada[1])>0&&Integer.parseInt(separada[1])<13&&
                            Integer.parseInt(separada[2])>1900)
                    {
                        try 
                        {
                            fechaB=formato.parse((fechaBruta));
                            System.out.println(formato.format(fechaB));
                        } 
                        catch (ParseException ex) {
                            ex.printStackTrace();
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Formato de fecha incorrecto","Formato de fecha incorrecto",JOptionPane.ERROR_MESSAGE);
                        fechaBajaTxt.setText("");
                        vacio=false;
                    }
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Solo se pueden poner números del 0 al 9","Formato de fecha incorrecto",JOptionPane.ERROR_MESSAGE);
                    fechaBajaTxt.setText("");
                    vacio=false;
                }
            }
            
            if(!vacio)
                JOptionPane.showMessageDialog(null,"Hay campos obligatorios sin completar","Campos vacíos",JOptionPane.ERROR_MESSAGE);
            else
            {
                int idR=Integer.parseInt(idReservaActividadTxt.getText());
                int idEstado= Integer.parseInt(idEstadoReservaActTxt.getText());
                int idClienteReser= Integer.parseInt(idClienteReservaActTxt.getText());
                int idActividad= Integer.parseInt(idActividadTxt.getText());
                int idReservaHora= Integer.parseInt(idReservaHoraActTxt.getText());
                if(!crear)
                    guardarDatos(idR, fechaR, fechaB, idEstado,idClienteReser,idActividad,idReservaHora);
                else
                {
                    sNuevaLinea=(idR+";"+formato.format(fechaR)+";"+ formato.format(fechaB)+";"+ idEstado+";"+idClienteReser+";"+idActividad+";"+idReservaHora);
                    modificar(sAntiguaLinea,sNuevaLinea);
                }
                JOptionPane.showMessageDialog(null, "Actividad reservada correctamente");
                idReservaActividadTxt.setText("");
                fechaReservaTxt.setText("");
                fechaBajaTxt.setText("");
                idEstadoReservaActTxt.setText("");
                idClienteReservaActTxt.setText("");
                idActividadTxt.setText("");
                idReservaHoraActTxt.setText("");
                
            
            }
        } catch (IOException ex) {
            Logger.getLogger(PanelReservaActividades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblAgregarMouseClicked
public void  guardarDatos(int idR,Date fechaR,Date fechaB,int idEstado,int idClienteReser, int idAct,int idReservaHoraAct){
        try
        {
           FileWriter F1=new FileWriter("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoReservaActividades.txt",true);
           PrintWriter pw= new PrintWriter(F1);
           pw.println(idR+";"+formato.format(fechaR)+";"+formato.format(fechaB)+";"+idEstado+";"+idClienteReser+";"+idAct+";"+idReservaHoraAct);
           pw.close();
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error al grabar el archivo");
        }
    }
    
    public static  void modificar(String lineaAntigua, String nuevaLinea){ 
       
       File fAntiguo= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoReservaActividades.txt");
       File fNuevo= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\temporal.txt");
       String aCadena=lineaAntigua;
       String nCadena=nuevaLinea;
       
       BufferedReader br;
        try {
            if(fAntiguo.exists())
            {
                br=new BufferedReader(new FileReader(fAntiguo));
                String linea;
                while((linea=br.readLine()) != null)
                {
                    if(linea.equals(aCadena)){
                        escribir(fNuevo, nCadena);
                    }
                        
                    else{
                        escribir(fNuevo, linea);
                    }
                        
                }
                br.close();
                String nAntiguo=fAntiguo.getName();
                File auxiliar= new File(fAntiguo.getAbsolutePath());
                borrar(fAntiguo);
                System.out.println(fNuevo.renameTo(auxiliar));
            }
            else
                System.out.println("Archivo no existe");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public static void escribir(File Ffichero,String cadena)
    {
        BufferedWriter bw;
        try 
        {
            if(!Ffichero.exists())
                Ffichero.createNewFile();
            bw= new BufferedWriter(new FileWriter(Ffichero,true));
            bw.write(cadena+"\r\n");
            bw.close();
        }
        catch (Exception ex) {
              ex.printStackTrace();
           } 
    }
    public static  void borrar(File Ffichero){
        try {

            if(Ffichero.exists())
            {
                System.out.println(Ffichero.delete());
            }
            } 
           catch (Exception ex) { 
             System.out.println(ex.getMessage());
        }
    }
    public boolean revisarEnArchivo(File archivo, int id)
    {
        if (!archivo.exists()) {
            return false;
        }
        else
        {
            try 
            {
                Scanner s=new Scanner(archivo);
                Scanner sl = null;
                while(s.hasNextLine())
                {
                  String linea= s.nextLine();
                  sl= new Scanner(linea);
                  sl.useDelimiter("\\s*;\\s*");
                  if(id==Integer.parseInt(sl.next()))
                      return true;
                  else
                      return false;
                } 
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(PanelSalas.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaBajaTxt;
    private javax.swing.JTextField fechaReservaTxt;
    private javax.swing.JTextField idActividadTxt;
    private javax.swing.JTextField idClienteReservaActTxt;
    private javax.swing.JTextField idEstadoReservaActTxt;
    private javax.swing.JTextField idReservaActividadTxt;
    private javax.swing.JTextField idReservaHoraActTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblDinamico;
    // End of variables declaration//GEN-END:variables
}
