/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;

public class PanelConsultaUsuario extends javax.swing.JPanel {

    DefaultTableModel Tabla;
    
    public PanelConsultaUsuario() {
        initComponents();
        Tabla=( DefaultTableModel)this.jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Consultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPorNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 30));

        jLabel1.setText("Por Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        txtPorNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorNombreActionPerformed(evt);
            }
        });
        add(txtPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 600, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Login Usuario", "Contrasena", "Nivel Acceso", "Nombre", "Apellido", "Correo Electronico"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 600, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        Tabla.setRowCount(0);
        String Nombre, Apellido, LoginUsuario,CorreoElectronico,NiveldeAcceso,contrasena;
        File arch= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoUsuarios.txt");
        
        try
	{
	if(arch.exists())
	{

	String linea;

       Scanner s = new Scanner(arch);
      while (s.hasNextLine())
	{
	linea = s.nextLine();
	Scanner k = new Scanner(linea);
	k.useDelimiter("\\s*;\\s*");
	LoginUsuario=k.next();
        contrasena=k.next();
	NiveldeAcceso=k.next();
	Nombre=k.next();
	Apellido=k.next();
        CorreoElectronico=k.next();
        contrasena="********";
        Tabla.addRow(new Object [] {LoginUsuario,contrasena,NiveldeAcceso,Nombre,Apellido,CorreoElectronico});
       
        }//FIN while
           
           s.close();
          }           
        }           
       catch(Exception x)
       {
         System.out.println(x);
       }

    }//GEN-LAST:event_ConsultarActionPerformed

    private void txtPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorNombreActionPerformed
       Tabla.setRowCount(0);
       
      String Nombre, Apellido, LoginUsuario,contrasena,CorreoElectronico,NiveldeAcceso;
      String nomb=txtPorNombre.getText();
      
      File arch= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoUsuarios.txt");
      
      try
      {
         if(arch.exists())
       {
          String linea;
          Scanner s = new Scanner(arch);
          while (s.hasNextLine())
     
         {
         linea = s.nextLine();    
         Scanner k = new Scanner(linea);
        k.useDelimiter("\\s*;\\s*");
	LoginUsuario=k.next();
        contrasena=k.next();
	NiveldeAcceso=k.next();
	Nombre=k.next();
	Apellido=k.next();
        CorreoElectronico=k.next();
        contrasena="********";
       
         
         if (linea.contains(nomb))
         {
      Tabla.addRow(new Object [] {LoginUsuario,contrasena,NiveldeAcceso,Nombre,Apellido,CorreoElectronico});
          
         }
         
      }// fin While  
          s.close();
          }
         }
       catch(FileNotFoundException x)
        {
          System.out.println(x);  
        }
    }//GEN-LAST:event_txtPorNombreActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPorNombre;
    // End of variables declaration//GEN-END:variables
}
