/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import Placeholder.TextPrompt;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Marte
 */
public class PanelReservas extends javax.swing.JPanel {

    /**
     * Creates new form PanelReservas
     */
    public PanelReservas() {
        initComponents();
        TextPrompt placeholderIdReserva= new TextPrompt("Obligatorio",idReservaTxt);
        TextPrompt placeholderIdSalaReserva= new TextPrompt("Obligatorio",idSalaReservaTxt);
        TextPrompt placeholderIdClienteReserva= new TextPrompt("Obligatorio",idClienteReservaTxt);
        TextPrompt placeholderHorarioReserva= new TextPrompt("Obligatorio",horarioReservaTxt);
        TextPrompt placeholderFechaReserva= new TextPrompt("Obligatorio     DD/MM/AA",fechaReservaTxt);
        TextPrompt placeholderEstadoReserva= new TextPrompt("Obligatorio",estadoReservaTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idSalaReservaTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        idClienteReservaTxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        fechaReservaTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblAgregar = new javax.swing.JLabel();
        lblDinamico = new javax.swing.JLabel();
        idReservaTxt = new javax.swing.JTextField();
        horarioReservaTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        estadoReservaTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Registrar nueva Reserva");
        jLabel10.setOpaque(true);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Reserva");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        idSalaReservaTxt.setBorder(null);
        add(idSalaReservaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 233, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID Sala Reserva");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, 250, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID Cliente Reserva");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        idClienteReservaTxt.setBorder(null);
        add(idClienteReservaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 233, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 250, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 10, 340));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Fecha Reserva");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 79, -1, -1));

        fechaReservaTxt.setBorder(null);
        add(fechaReservaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 233, 20));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 230, 10));

        lblAgregar.setBackground(new java.awt.Color(0, 0, 0));
        lblAgregar.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setText("AGREGAR");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setOpaque(true);
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });
        add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 130, 40));
        add(lblDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 80, 20));

        idReservaTxt.setBorder(null);
        idReservaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReservaTxtActionPerformed(evt);
            }
        });
        add(idReservaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 233, 20));

        horarioReservaTxt.setBorder(null);
        add(horarioReservaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 233, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Horario de reserva");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 250, -1));

        estadoReservaTxt.setBorder(null);
        add(estadoReservaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 233, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Estado de reserva");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void idReservaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReservaTxtActionPerformed
        int cod;
        cod=Integer.parseInt(idReservaTxt.getText());
        boolean encontrado=false;
        File archivoReservas= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoReservas.txt");
        Scanner s;    
            try {
                s= new Scanner(archivoReservas);
                if(!archivoReservas.exists())
                {
                    archivoReservas.createNewFile();
                }
                while(s.hasNext()&&!encontrado)
                {
                    String linea=s.nextLine();
                    Scanner sl= new Scanner(linea);
                    sl.useDelimiter("\\s*;\\s*");
                    if(cod==Integer.parseInt(sl.next())){
                        idSalaReservaTxt.setText(sl.next());
                        idClienteReservaTxt.setText(sl.next());
                        fechaReservaTxt.setText(sl.next());
                        horarioReservaTxt.setText(sl.next());
                        estadoReservaTxt.setText(sl.next());
                        lblDinamico.setText("Modificando");
                        encontrado=true;
                    }
                    else{
                        lblDinamico.setText("Creando");
                        idSalaReservaTxt.setText("");
                        idClienteReservaTxt.setText("");
                        fechaReservaTxt.setText("");
                        horarioReservaTxt.setText("");
                        estadoReservaTxt.setText("");
                    }
                }
                s.close();
               
            } 
            catch (FileNotFoundException e)
            {
                JOptionPane.showMessageDialog(null, "Archivo de texto no encontrado");
            } catch (IOException ex) 
            {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_idReservaTxtActionPerformed

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        boolean vacio=true;
        if(idReservaTxt.getText().equals("")||idSalaReservaTxt.getText().equals("")||idClienteReservaTxt.getText().equals("")
            ||fechaReservaTxt.getText().equals("")||horarioReservaTxt.getText().equals("")||estadoReservaTxt.getText().equals(""))
            vacio=false;
       
        if(!vacio)
            JOptionPane.showMessageDialog(null,"Hay campos obligatorios sin completar","Campos vacíos",JOptionPane.ERROR_MESSAGE);
        else
        {
            File archivoReservas= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoReservas.txt");
            try {                           
                if(!archivoReservas.exists())
                    archivoReservas.createNewFile();;
                
                BufferedWriter bw=new BufferedWriter(new FileWriter(archivoReservas));
               
                bw.write(idReservaTxt.getText()+";"+idSalaReservaTxt.getText()+";"+idClienteReservaTxt.getText()+";"+fechaReservaTxt.getText()+
                        horarioReservaTxt.getText()+";"+estadoReservaTxt.getText());
                bw.newLine();
                bw.flush();
               
            } 
            catch (FileNotFoundException e)
            {
                JOptionPane.showMessageDialog(null, "Archivo de texto no encontrado");
            } catch (IOException ex) 
            {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Reserva agregada correctamente");
            idClienteReservaTxt.setText("");
            idReservaTxt.setText("");
            idSalaReservaTxt.setText("");
            fechaReservaTxt.setText("");
            horarioReservaTxt.setText("");
            estadoReservaTxt.setText("");
    }//GEN-LAST:event_lblAgregarMouseClicked
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField estadoReservaTxt;
    private javax.swing.JTextField fechaReservaTxt;
    private javax.swing.JTextField horarioReservaTxt;
    private javax.swing.JTextField idClienteReservaTxt;
    private javax.swing.JTextField idReservaTxt;
    private javax.swing.JTextField idSalaReservaTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblDinamico;
    // End of variables declaration//GEN-END:variables
}
