
package form;

import Placeholder.TextPrompt;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Marte
 */
public class PanelActividades extends javax.swing.JPanel {

    public static String sAntiguaLinea="";
    public static String sNuevaLinea="";
    public static boolean crear;
    /**
     * Creates new form PanelActividades
     */
    public PanelActividades() {
        initComponents();
        TextPrompt placeholderIdActividad= new TextPrompt("Obligatorio, debe contener 8 dígitos",idActividadTxt);
        TextPrompt placeholderNombreActividad= new TextPrompt("Obligatorio",nombreActividadTxt);
        TextPrompt placeholderDescripcionAct= new TextPrompt("Obligatorio",descripcionActividad);
        TextPrompt placeholderIdLocalizacion= new TextPrompt("Obligatorio, debe contener 8 dígitos",idLocalizacionActTxt);
        TextPrompt placeholderIdEntrenador= new TextPrompt("Obligatorio, debe contener 8 dígitos",idEntrenadorActTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreActividadTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        descripcionActividad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        idLocalizacionActTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idEntrenadorActTxt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblAgregar = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblDinamico = new javax.swing.JLabel();
        idActividadTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Registrar nueva Actividad");
        jLabel10.setOpaque(true);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Actividad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        nombreActividadTxt.setBackground(new java.awt.Color(255, 255, 255));
        nombreActividadTxt.setBorder(null);
        add(nombreActividadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 233, 17));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre Actividad");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, 250, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Descripcion Actividad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        descripcionActividad.setBackground(new java.awt.Color(255, 255, 255));
        descripcionActividad.setBorder(null);
        add(descripcionActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 233, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 250, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 10, 340));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("ID Localización Actividad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 79, -1, -1));

        idLocalizacionActTxt.setBackground(new java.awt.Color(255, 255, 255));
        idLocalizacionActTxt.setBorder(null);
        add(idLocalizacionActTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 99, 233, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ID Entrenador Actividad");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 155, -1, -1));

        idEntrenadorActTxt.setBackground(new java.awt.Color(255, 255, 255));
        idEntrenadorActTxt.setBorder(null);
        add(idEntrenadorActTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 194, 233, 20));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 230, 10));

        lblAgregar.setBackground(new java.awt.Color(0, 0, 0));
        lblAgregar.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setText("AGREGAR");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setOpaque(true);
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });
        add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 130, 40));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 230, 10));
        add(lblDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 80, 20));

        idActividadTxt.setBackground(new java.awt.Color(255, 255, 255));
        idActividadTxt.setBorder(null);
        idActividadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActividadTxtActionPerformed(evt);
            }
        });
        add(idActividadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 233, 17));
    }// </editor-fold>//GEN-END:initComponents

    private void idActividadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActividadTxtActionPerformed
        String cod;
        boolean encontrado=false;
        cod=idActividadTxt.getText();
        Scanner s;
        Scanner sl = null;
        try 
        {
          File f= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoActividades.txt");
          
          if(!f.exists())
          {
              f.createNewFile();
          }
          
            try {
                s=new Scanner(f);
              while(s.hasNextLine()&&!encontrado)
              {
                  String linea= s.nextLine();
                  sl= new Scanner(linea);
                  sl.useDelimiter("\\s*;\\s*");
                  try 
                  {
                      if(cod.equals(sl.next()))
                      {
                          nombreActividadTxt.setText(sl.next());
                          descripcionActividad.setText(sl.next());
                          idLocalizacionActTxt.setText(sl.next());
                          idEntrenadorActTxt.setText(sl.next());
                          crear=true;
                          encontrado=true;
                          sAntiguaLinea=(idActividadTxt.getText()+";"+nombreActividadTxt.getText()+";"+descripcionActividad.getText()
                                  +";"+idLocalizacionActTxt.getText()+";"+idEntrenadorActTxt.getText());
                          lblDinamico.setText("Modificando");
                      }
                      else
                      {
                          nombreActividadTxt.setText("");
                          descripcionActividad.setText("");
                          idLocalizacionActTxt.setText("");
                          idEntrenadorActTxt.setText("");
                          crear=false;
                          encontrado=false;
                          lblDinamico.setText("Creando");
                      }
                  } catch (Exception e) {
                      System.out.println("Error al leer el archivo ");
                      e.printStackTrace();
                  }
              }
              
                  sl.close();
                  s.close();
            } 
            catch (NullPointerException e) {
                lblDinamico.setText("Creando");
            }
          
        } 
        catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_idActividadTxtActionPerformed

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        try {
            File f= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoActividades.txt");
            boolean vacio=true;
            
            if(!f.exists())
                f.createNewFile();
            if(idActividadTxt.getText().equals("")||nombreActividadTxt.getText().equals("")||descripcionActividad.getText().equals("")
                    ||idLocalizacionActTxt.getText().equals("")||idEntrenadorActTxt.getText().equals(""))
                vacio=false;
            if(!idActividadTxt.getText().matches("[0-9]{8}"))//.matches taoma una sub region de algo, en este caso números enteros del 0 al 9
            {
                vacio=false;
                idActividadTxt.setText("");
                JOptionPane.showMessageDialog(null,"El id de la actividad solo acepta valores numéricos enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            if(nombreActividadTxt.getText().length()<5)
            {
                vacio=false;
                nombreActividadTxt.setText("");
                JOptionPane.showMessageDialog(null,"El nombre de la actividad debe contener al menos 5 caracteres","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
                
            }
            if(descripcionActividad.getText().length()<10)
            {
                vacio=false;
                descripcionActividad.setText("");
                JOptionPane.showMessageDialog(null,"El nombre de la actividad debe contener al menos 10 caracteres","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
                
            }
            
            if(!idLocalizacionActTxt.getText().matches("[0-9]{8}"))//.matches taoma una sub region de algo, en este caso números enteros del 0 al 9
            {
                vacio=false;
                idLocalizacionActTxt.setText("");
                JOptionPane.showMessageDialog(null,"El id de la localización de la actividad solo acepta valores numéricos enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                File archId= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoLocalizacion.txt");
                if (!archId.exists()) 
                {
                    JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                    vacio=false;
                }
                else
                {
                    String cod;
                    cod=idLocalizacionActTxt.getText();
                    if(!revisarEnArchivo(archId, cod))
                    {
                        idLocalizacionActTxt.setText("");
                        JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                        vacio=false;
                    }
                }
                
            }
            
            if(!idEntrenadorActTxt.getText().matches("[0-9]{8}"))//.matches taoma una sub region de algo, en este caso números enteros del 0 al 9
            {
                vacio=false;
                idEntrenadorActTxt.setText("");
                JOptionPane.showMessageDialog(null,"El id del entrenador de la actividad solo acepta valores numéricos enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                File archId= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoEntrenador.txt");
                if (!archId.exists()) 
                {
                    JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                    vacio=false;
                }
                else
                {
                    String cod;
                    cod=idEntrenadorActTxt.getText();
                    if(!revisarEnArchivo(archId, cod))
                    {
                        idEntrenadorActTxt.setText("");
                        JOptionPane.showMessageDialog(null,"El archivo del id no existe, cree una el id en el respectivo mantenimiento","Archivo inexistente",JOptionPane.ERROR_MESSAGE);
                        vacio=false;
                    }
                }
                
            }
            
            if(!vacio)
                JOptionPane.showMessageDialog(null,"Hay campos obligatorios sin completar","Campos vacíos",JOptionPane.ERROR_MESSAGE);
            else
            {
                String idActividad=idActividadTxt.getText();
                String nombre=nombreActividadTxt.getText();
                String descripcion=descripcionActividad.getText();
                String idLocalizacion=idLocalizacionActTxt.getText();
                String idEntrenador=idEntrenadorActTxt.getText();
                if(!crear)
                    guardarDatos(idActividad, nombre,descripcion,idLocalizacion,idEntrenador);
                else
                {
                    sNuevaLinea=(idActividad+";"+nombre+";"+idLocalizacion+";"+descripcion);
                    modificar(sAntiguaLinea,sNuevaLinea);
                }
                JOptionPane.showMessageDialog(null, "Sala agregada correctamente");
                nombreActividadTxt.setText("");
                descripcionActividad.setText("");
                idActividadTxt.setText("");
                idLocalizacionActTxt.setText("");
                idEntrenadorActTxt.setText("");
                lblDinamico.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(PanelActividades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblAgregarMouseClicked
public void  guardarDatos(String idActividad,String nombre, String descripcion,String idLocalizacion, String idEntrenador){
        try
        {
           FileWriter F1=new FileWriter("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoActividades.txt",true);
           PrintWriter pw= new PrintWriter(F1);
           pw.println(idActividad+";"+nombre+";"+descripcion+";"+idLocalizacion+";"+idEntrenador);
           pw.close();
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Error al grabar el archivo");
        }
    }
    
    public static  void modificar(String lineaAntigua, String nuevaLinea){ 
       
       File fAntiguo= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoActividades.txt");
       File fNuevo= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\temporal.txt");
       String aCadena=lineaAntigua;
       String nCadena=nuevaLinea;
       
       BufferedReader br;
        try {
            if(fAntiguo.exists())
            {
                br=new BufferedReader(new FileReader(fAntiguo));
                String linea;
                while((linea=br.readLine()) != null)
                {
                    if(linea.equals(aCadena)){
                        escribir(fNuevo, nCadena);
                    }
                        
                    else{
                        escribir(fNuevo, linea);
                    }
                        
                }
                br.close();
                File auxiliar= new File(fAntiguo.getAbsolutePath());
                borrar(fAntiguo);
                System.out.println(fNuevo.renameTo(auxiliar));
            }
            else
                System.out.println("Archivo no existe");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
            
   
    
    public static void escribir(File Ffichero,String cadena)
    {
        BufferedWriter bw;
        try 
        {
            if(!Ffichero.exists())
                Ffichero.createNewFile();
            bw= new BufferedWriter(new FileWriter(Ffichero,true));
            bw.write(cadena+"\r\n");
            bw.close();
        }
        catch (Exception ex) {
              ex.printStackTrace();
           } 
    }
    public static  void borrar(File Ffichero){
        try {

            if(Ffichero.exists())
            {
                System.out.println(Ffichero.delete());
            }
            } 
           catch (Exception ex) { 
             System.out.println(ex.getMessage());
        }
    }
     public boolean revisarEnArchivo(File archivo, String id)
    {
        if (!archivo.exists()) {
            return false;
        }
        else
        {
            try 
            {
                Scanner s=new Scanner(archivo);
                Scanner sl = null;
                while(s.hasNextLine())
                {
                  String linea= s.nextLine();
                  sl= new Scanner(linea);
                  sl.useDelimiter("\\s*;\\s*");
                  if(id.equals(sl.next()))
                      return true;
                  else
                      return false;
                } 
            }
            catch (FileNotFoundException ex) {
                Logger.getLogger(PanelSalas.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descripcionActividad;
    private javax.swing.JTextField idActividadTxt;
    private javax.swing.JTextField idEntrenadorActTxt;
    private javax.swing.JTextField idLocalizacionActTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblDinamico;
    private javax.swing.JTextField nombreActividadTxt;
    // End of variables declaration//GEN-END:variables
}
