
package form;

import Placeholder.TextPrompt;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Marte
 */
public class PanelEntrenador extends javax.swing.JPanel {

    /**
     * Creates new form PanelEntrenador
     */
    public PanelEntrenador() {
        initComponents();
        TextPrompt placeholderId= new TextPrompt("Obligatorio",idTxt);
        TextPrompt placeholderNombre= new TextPrompt("Obligatorio",nombreTxt);
        TextPrompt placeholderApellidos= new TextPrompt("Obligatorio",apellidosTxt);
        TextPrompt placeholderTelefono= new TextPrompt("Obligatorio",telefonoTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        correoElectronicoTxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        apellidosTxt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblAgregar = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        lblDinamico = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(590, 321));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 20, -1));

        nombreTxt.setBorder(null);
        add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 233, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 233, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 233, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Correo Electronico:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        correoElectronicoTxt.setBorder(null);
        add(correoElectronicoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 233, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 230, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        telefonoTxt.setBorder(null);
        add(telefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 233, 20));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 230, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Apellidos:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        apellidosTxt.setBorder(null);
        add(apellidosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 233, 20));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 230, 10));

        lblAgregar.setBackground(new java.awt.Color(0, 0, 0));
        lblAgregar.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setText("AGREGAR");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setOpaque(true);
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });
        add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 130, 40));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 10, 280));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Registrar nuevo Entrenador");
        jLabel10.setOpaque(true);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 40));
        add(lblDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 80, 20));

        idTxt.setBorder(null);
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 233, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        boolean vacio=true;
        if(idTxt.getText().equals("")||nombreTxt.getText().equals("")||apellidosTxt.getText().equals(""))
            vacio=false;
       
        if(!vacio)
            JOptionPane.showMessageDialog(null,"Hay campos obligatorios sin completar","Campos vacíos",JOptionPane.ERROR_MESSAGE);
        else
        {
            File archivoEntrenador= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoEntrenador.txt");
            try {                           
                if(!archivoEntrenador.exists())
                    archivoEntrenador.createNewFile();;
                
                BufferedWriter bw=new BufferedWriter(new FileWriter(archivoEntrenador));

                bw.write(idTxt.getText()+";"+nombreTxt.getText()+";"+apellidosTxt.getText()+";"+telefonoTxt.getText()
                +";"+correoElectronicoTxt.getText());
                bw.newLine();
                bw.flush();
               
            } 
            catch (FileNotFoundException e)
            {
                JOptionPane.showMessageDialog(null, "Archivo de texto no encontrado");
            } catch (IOException ex) 
            {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Usuario agregado correctamente");
            idTxt.setText("");
            telefonoTxt.setText("");
            nombreTxt.setText("");
            apellidosTxt.setText("");
            correoElectronicoTxt.setText("");
        }
    }//GEN-LAST:event_lblAgregarMouseClicked

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        int cod;
        cod=Integer.parseInt(idTxt.getText());
        boolean encontrado=false;
        File archivoEntrenador= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoEntrenador.txt");
        Scanner s;    
            try {
                s= new Scanner(archivoEntrenador);
                if(!archivoEntrenador.exists())
                {
                    archivoEntrenador.createNewFile();
                }
                while(s.hasNext()&&!encontrado)
                {
                    String linea=s.nextLine();
                    Scanner sl= new Scanner(linea);
                    sl.useDelimiter("\\s*;\\s*");
                    if(cod==Integer.parseInt(sl.next())){
                        nombreTxt.setText(sl.next());
                        apellidosTxt.setText(sl.next());
                        telefonoTxt.setText(sl.next());
                        correoElectronicoTxt.setText(sl.next());
                        lblDinamico.setText("Modificando");
                        encontrado=true;
                    }
                    else{
                        lblDinamico.setText("Creando");
                        nombreTxt.setText("");
                        apellidosTxt.setText("");
                        telefonoTxt.setText("");
                        correoElectronicoTxt.setText("");
                    }
                }
                s.close();
               
            } 
            catch (FileNotFoundException e)
            {
                JOptionPane.showMessageDialog(null, "Archivo de texto no encontrado");
            } catch (IOException ex) 
            {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_idTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTxt;
    private javax.swing.JTextField correoElectronicoTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblDinamico;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables
}
