
package form;

import Placeholder.TextPrompt;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Marte
 */
public class PanelEstadoReserva extends javax.swing.JPanel {
    public static String sAntiguaLinea="";
    public static String sNuevaLinea="";
    public static boolean crear;
    public static String estado="";
    /**
     * Creates new form PanelEstadoReserva
     */
    public PanelEstadoReserva() {
        initComponents();
        TextPrompt placeholderEstadoReserva= new TextPrompt("Obligatorio, debe contener 8 dígitos",idEstadoReserva);
        grupoEstado.add(reservado);
        grupoEstado.add(noReservado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEstado = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idEstadoReserva = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblAgregar = new javax.swing.JLabel();
        lblDinamico = new javax.swing.JLabel();
        reservado = new javax.swing.JCheckBox();
        noReservado = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Registrar nuevo Estado Reserva");
        jLabel10.setOpaque(true);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Estado de Reserva");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        idEstadoReserva.setBorder(null);
        idEstadoReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEstadoReservaActionPerformed(evt);
            }
        });
        add(idEstadoReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 233, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 10, 150));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Estado");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 230, 10));

        lblAgregar.setBackground(new java.awt.Color(0, 0, 0));
        lblAgregar.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregar.setText("AGREGAR");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.setOpaque(true);
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });
        add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 130, 40));
        add(lblDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 80, 20));

        reservado.setText("Reservado");
        add(reservado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        noReservado.setSelected(true);
        noReservado.setText("No reservado");
        add(noReservado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void idEstadoReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEstadoReservaActionPerformed
        int cod;
        cod=Integer.parseInt(idEstadoReserva.getText());
        boolean encontrado=false;
        File f= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoEstadoReserva.txt");
        Scanner s;    
        Scanner sl=null;
            try {
                
                if(!f.exists())
                    f.createNewFile();
                s= new Scanner(f);
                while(s.hasNext()&&!encontrado)
                {
                    String linea=s.nextLine();
                    sl= new Scanner(linea);
                    sl.useDelimiter("\\s*;\\s*");
                    try 
                    {
                        if(cod==Integer.parseInt(sl.next())){
                        if(sl.next().equals("reservado"))
                        {
                            estado="reservado";
                            reservado.setSelected(true);
                        }
                        else
                        {
                            estado="no reservado";
                            noReservado.setSelected(true);
                        }
                            
                        lblDinamico.setText("Modificando");
                        sAntiguaLinea=(idEstadoReserva.getText()+";"+estado);
                        encontrado=true;
                        crear=true;
                    }
                    else{
                        lblDinamico.setText("Creando");
                        noReservado.setSelected(true);
                        crear=false;
                    }
                    } catch (Exception e) 
                    {
                        System.out.println("Error al leer el archivo ");
                        e.printStackTrace();
                    }
                }
                s.close();
                sl.close();
            }
            catch (NullPointerException e) {
                lblDinamico.setText("Creando");
            }
            catch (IOException ex) 
            {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_idEstadoReservaActionPerformed

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        try {
            boolean vacio=true;
            File f= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoEstadoReserva.txt");
            if(!f.exists())
                f.createNewFile();
            if(idEstadoReserva.getText().equals(""))
                vacio=false;
            if(!idEstadoReserva.getText().matches("[0-9]{8}"))//.matches taoma una sub region de algo, en este caso números enteros del 0 al 9
            {
                vacio=false;
                idEstadoReserva.setText("");
                JOptionPane.showMessageDialog(null,"El id de la localización solo acepta valores númerios enteros","Valor incorrecto",JOptionPane.ERROR_MESSAGE);
            }
            if(!vacio)
                JOptionPane.showMessageDialog(null,"Hay campos obligatorios sin completar","Campos vacíos",JOptionPane.ERROR_MESSAGE);
            else 
            {
                File estadoReserva= new File("C:\\-JohanGTS-ProyectoFinalLabProg_2\\src\\ArchivosDeTexto\\archivoEstadoReserva.txt");
                try
                {
                    if(!estadoReserva.exists())
                        estadoReserva.createNewFile();
                    BufferedWriter bw=new BufferedWriter(new FileWriter(estadoReserva));
                    if(reservado.isSelected())
                        estado="reservado";
                    else
                        estado="no reservado";
                    bw.write(idEstadoReserva.getText()+";"+estado);
                    bw.newLine();
                    bw.flush();
                }
                catch (FileNotFoundException e)
                {
                    JOptionPane.showMessageDialog(null, "Archivo de texto no encontrado");
                }
                catch(IOException e)
                {
                    e.printStackTrace();
                }
                
                JOptionPane.showMessageDialog(null, "Estado de reserva agregado correctamente");
                idEstadoReserva.setText("");
                noReservado.setSelected(true);
                lblDinamico.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(PanelEstadoReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblAgregarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoEstado;
    private javax.swing.JTextField idEstadoReserva;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblDinamico;
    private javax.swing.JCheckBox noReservado;
    private javax.swing.JCheckBox reservado;
    // End of variables declaration//GEN-END:variables
}
